#!/usr/bin/with-contenv bash

while [ -d "/cloud/Data" ]; do
  sleep 15
done

  echo "plexdrive folder no longer connected.  Need to re-establish connection"
  exec s6-setuidgid abc fusermount -u /tv
  exec s6-setuidgid abc fusermount -u /movies
  exec s6-setuidgid abc fusermount -u /plexdrive-decrypt
  exec s6-setuidgid abc fusermount -u /plexdrive-newdecrypt
  exec s6-setuidgid abc fusermount -u /cloud

pd_mountpoint=$(if ! mountpoint -q /local; then echo /data; else echo /cloud; fi)

pd_basic_opts="
-c /config/
--cache-file=/cache/cache.bolt
--uid=${PUID:-911}
--gid=${PGID:-911}
--umask=0100775
-o allow_other
"

IFS=" " read -r -a pd_user_opts <<< "$PLEXDRIVE_OPTS"

mount_command="plexdrive mount ${pd_mountpoint} $(echo $pd_basic_opts) ${pd_user_opts[@]}"
echo "executing => $mount_command"
exec s6-setuidgid abc $mount_command
