#!/usr/bin/with-contenv bash

. /etc/default/nfs-kernel-server
. /etc/default/nfs-common

        # Edit the /etc/default/nfs-kernel-server to fix the rpc mount port
        sed -i '/RPCMOUNT/d' /etc/default/nfs-kernel-server
        echo 'RPCMOUNTDOPTS="--port 20048"' >> /etc/default/nfs-kernel-server

        # add the /tv directory to the nfs exports
        echo " Adding /tv to the list of /etc/exports"
        echo "/tv *(rw,sync,no_subtree_check,fsid=1001,no_root_squash)" >> /etc/exports

        # add the /movies directory to the nfs exports
        echo " Adding /movies to the list of /etc/exports"
        echo "/movies *(rw,sync,no_subtree_check,fsid=1002,no_root_squash)" >> /etc/exports

rpcbind
service nfs-kernel-server start
# update the exportfs
        #exec exportfs -ra

